#' Create columns, but only if they are missing
#'
#' Adds columns using [dplyr::mutate()], but only if they are absent in the
#' provided data frame.
#'
#' @inherit dplyr::mutate
#' @family helper functions
#' @noRd
#' @examples
#' # Column "space" is not present yet, so it is added
#' mutate_when_missing(cars, space = "The final frontier")
#' # Column "speed" is present, so it is not added
#' mutate_when_missing(cars, speed = "warp 9")
mutate_when_missing <- function(.data, ...) {
  dots <- substitute(list(...))[-1]
  cols_to_check <- names(sapply(dots, deparse))
  columns_to_add <- cols_to_check[!cols_to_check %in% colnames(.data)]
  if (!rlang::is_empty(columns_to_add)) {
    .data <- dplyr::mutate(.data, ...)
  }
  return(.data)
}

#' Create hashes
#'
#' Set a vectorised function for creating hash function digests, using algorithm
#' "crc32".
#'
#' @param object vector or character string
#' @return hash summary as a character vector of the same length as the input
#' @family helper functions
#' @noRd
#' @examples
#' vdigest_crc32(c("00a2c20d", "29b7d356"))
vdigest_crc32 <- function(object) {
  vdigest_crc32 <- digest::getVDigest(algo = "crc32")
  return(vdigest_crc32(object))
}

#' Generate and replace deploymentID's
#'
#' Replaces deploymentIDs in deployments, media and observations, with hashes
#' generated by `vdigest_crc32`.
#'
#' @inheritParams print.camtrapdp
#' @param deploymentID deploymentID's to be replaced. Either a single ID or a
#' vector of ID's.
#' @return `x` with replaced deploymentID's
#' @family helper functions
#' @noRd
#' @examples
#' x_replaced <-
#' generate_deploymentID(example_dataset(), c("00a2c20d", "29b7d356"))
#' # Inspect results
#' deployments(x_replaced)$deploymentID
generate_deploymentID <- function(x, deploymentID) {

  # replace deploymentIDs in deployments
  deployments(x) <-
    deployments(x) %>%
    dplyr::mutate(
      deploymentID =
        dplyr::if_else(
          .data$deploymentID %in% {{ deploymentID }},
          vdigest_crc32(.data$deploymentID),
          .data$deploymentID
        )
    )

  # replace deploymentIDs in observations
  observations(x) <-
    observations(x) %>%
    dplyr::mutate(
      deploymentID =
        dplyr::if_else(
          .data$deploymentID %in% {{ deploymentID }},
          vdigest_crc32(.data$deploymentID),
          .data$deploymentID
        )
    )

  # replace deploymentIDs in media
  media(x) <-
    media(x) %>%
    dplyr::mutate(
      deploymentID =
        dplyr::if_else(
          .data$deploymentID %in% {{ deploymentID }},
          vdigest_crc32(.data$deploymentID),
          .data$deploymentID
        )
    )

  return(x)
}

#' Generate and replace mediaID's
#'
#' Replaces mediaIDs in media and observations, with hashes generated by
#' `vdigest_crc32`.
#'
#' @inheritParams print.camtrapdp
#' @param mediaID mediaID's to be replaced. Either a single ID or a vector of
#' ID's.
#' @return `x` with replaced mediaID's
#' @family helper functions
#' @noRd
#' @examples
#' generate_mediaID(example_dataset(), c("07840dcc", "401386c7"))
generate_mediaID <- function(x, mediaID) {

  # replace mediaIDs in media
  media(x) <-
    media(x) %>%
    dplyr::mutate(
      mediaID =
        dplyr::if_else(
          .data$mediaID %in% {{ mediaID }},
          vdigest_crc32(.data$mediaID),
          .data$mediaID
        )
    )

  # replaced mediaIDs in observations
  observations(x) <-
    observations(x) %>%
    dplyr::mutate(
      mediaID =
        dplyr::if_else(
          .data$mediaID %in% {{ mediaID }},
          vdigest_crc32(.data$mediaID),
          .data$mediaID
        )
    )

  return(x)
}

#' Generate and replace observationID's
#'
#' Replaces observationIDs in observations, with hashes generated by
#' `vdigest_crc32`.
#'
#' @inheritParams print.camtrapdp
#' @param observationID observationID's to be replaced. Either a single ID or a
#' vector of ID's.
#' @return `x` with replaced observationID's
#' @family helper functions
#' @noRd
#' @examples
#' generate_observationID(example_dataset(), c("705e6036", "07840dcc_1"))
generate_observationID <- function(x, observationID) {

  # replaced observationIDs in observations
  observations(x) <-
    observations(x) %>%
    dplyr::mutate(
      observationID =
        dplyr::if_else(
          .data$observationID %in% {{ observationID }},
          vdigest_crc32(.data$observationID),
          .data$observationID
        )
    )

  return(x)
}
